export const CURRENCIES_FAIL = 'CURRENCIES_FAIL'
export const CURRENCIES_SUCCESS = 'CURRENCIES_SUCCESS'
export const CURRENCIES_LOADING = 'CURRENCIES_LOADING'

export const SYMBOLS_FAIL = 'SYMBOLS_FAIL'
export const SYMBOLS_SUCCESS = 'SYMBOLS_SUCCESS'
export const SYMBOLS_LOADING = 'SYMBOLS_LOADING'

export const CURRENCY_CODES_FAIL = 'CURRENCY_CODES_FAIL'
export const CURRENCY_CODES_SUCCESS = 'CURRENCY_CODES_SUCCESS'
export const CURRENCY_CODES_LOADING = 'CURRENCY_CODES_LOADING'